"""Refresh the Tier 2 universe snapshot: `uv run python -m desk.collectors.universe`.

Reads the S&P 500 constituents table from Wikipedia's parse API and writes
config/universe_sp500.yaml. Run by hand when index membership changes; the file is
committed so the universe in use is visible in the repo.
"""

import sys
from datetime import UTC, datetime
from html.parser import HTMLParser
from pathlib import Path

import httpx
import yaml

from desk.collectors.base import USER_AGENT
from desk.config import CONFIG_DIR

WIKIPEDIA_API = "https://en.wikipedia.org/w/api.php"
PAGE = "List_of_S&P_500_companies"
TABLE_ID = "constituents"
MIN_EXPECTED = 490


class ConstituentsParser(HTMLParser):
    """Collects the first cell (ticker) of each row in the table with id="constituents"."""

    def __init__(self) -> None:
        super().__init__()
        self.symbols: list[str] = []
        self._table_depth = 0
        self._cell_index = -1
        self._in_first_cell = False
        self._cell_text: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "table":
            if self._table_depth:
                self._table_depth += 1
            elif dict(attrs).get("id") == TABLE_ID:
                self._table_depth = 1
            return
        if self._table_depth != 1:
            return
        if tag == "tr":
            self._cell_index = -1
        elif tag in ("td", "th"):
            self._cell_index += 1
            self._in_first_cell = tag == "td" and self._cell_index == 0
            self._cell_text = []

    def handle_endtag(self, tag: str) -> None:
        if tag == "table" and self._table_depth:
            self._table_depth -= 1
        elif tag == "td" and self._in_first_cell:
            symbol = "".join(self._cell_text).strip()
            if symbol:
                self.symbols.append(symbol)
            self._in_first_cell = False

    def handle_data(self, data: str) -> None:
        if self._in_first_cell:
            self._cell_text.append(data)


def parse_constituents(html: str) -> list[str]:
    parser = ConstituentsParser()
    parser.feed(html)
    return sorted(set(parser.symbols))


def fetch_constituents() -> list[str]:
    response = httpx.get(
        WIKIPEDIA_API,
        params={
            "action": "parse",
            "page": PAGE,
            "prop": "text",
            "format": "json",
            "formatversion": "2",
        },
        headers={"User-Agent": USER_AGENT},
        timeout=30.0,
    )
    response.raise_for_status()
    return parse_constituents(response.json()["parse"]["text"])


def write_universe(symbols: list[str], path: Path) -> None:
    document = {
        "source": f"Wikipedia: {PAGE.replace('_', ' ')}",
        "as_of": datetime.now(UTC).date().isoformat(),
        "symbols": symbols,
    }
    header = (
        "# Tier 2 universe. Generated by `python -m desk.collectors.universe`; edit by rerunning.\n"
    )
    path.write_text(header + yaml.safe_dump(document, sort_keys=False, width=100), encoding="utf-8")


def main() -> None:
    symbols = fetch_constituents()
    if len(symbols) < MIN_EXPECTED:
        # A layout change on the page would silently shrink the universe; refuse instead.
        sys.exit(f"parsed only {len(symbols)} symbols; expected at least {MIN_EXPECTED}")
    path = CONFIG_DIR / "universe_sp500.yaml"
    write_universe(symbols, path)
    print(f"wrote {len(symbols)} symbols to {path}")


if __name__ == "__main__":
    main()
